var mapaDeNavegacao = [
  {name: 'Tem discriminação em São Caetano?', video: 'MI8U5rQXUQs', pergunta: [100, 226, 92]},
  {name: 'Tem capoeira em São Caetano?', video: '3YbOkb5Sxi0', pergunta: [244, 28, 264]},
  {name: 'Tem história em São Caetano?', video: 'hHu1FwaooEs', pergunta: [53, 66, 85]},
  {name: 'Tem verticalização em São Caetano?', video: 'OjNVNLGH2kU', pergunta: [93, 87, 279]},
  {name: 'Tem cultura popular em São Caetano?', video: 'scAman4qeXo', pergunta: [249, 100, 97]},
  {name: 'Tem nordestinos em São Caetano?', video: '9acozs8E3ds', pergunta: [71, 48, 229]},
  {name: 'Tem memória em São Caetano?', video: 'hTffqEO37pQ', pergunta: [121, 101, 235]},
  {name: 'Tem presença indígena em São Caetano?', video: 'aG9e8L5rtgw', pergunta: [144, 149, 168]},
  {name: 'Tem religiões afro em São Caetano?', video: 'fRyxu2GBXc0', pergunta: [150, 160, 276]},
  {name: 'Tem racismo em São Caetano?', video: '32iuclrqm9A', pergunta: [215, 248, 220]},
  {name: 'Tem resistência em São Caetano?', video: '6P-umSJgVlQ', pergunta: [108, 260, 237]},
  {name: 'Tem negritude em São Caetano?', video: 'd7ZreTV_lNo', pergunta: [275, 66, 174]},
  {name: 'Como se imagina que é a população de São Caetano?', video: 'j1vZYKoDvKg', pergunta: [13, 86, 65]},
  {name: 'Como São Caetano representa a sua memória?', video: 'S_aodABI058', pergunta: [57, 69, 6]},
  {name: 'Como é a festa junina no nordeste?', video: '3G5XEt_9ROE', pergunta: [15, 63, 17]},
  {name: 'A cultura nordestina é respeitada na escola?', video: '5pyjd7ZqPJY', pergunta: [14, 44, 97]},
  {name: 'Como é a fogueira das viúvas?', video: 'IXgdUCnZzu0', pergunta: [14, 5, 193]},
  {name: 'Como é a comida nordestina?', video: 'dg7ecygyIlA', pergunta: [194, 62, 15]},
  {name: 'Como é o reisado?', video: 'bWDZb1g-4sc', pergunta: [16, 111, 4]},
  {name: 'Tem preconceito com a prática da capoeira?', video: 'lxTwvKxq6WY', pergunta: [99, 30, 226]},
  {name: 'Dá para reconhecer quem tem preconceito?', video: '4EcUJUVbOio', pergunta: [25, 103, 112]},
  {name: 'Quais os tipos de capoeira?', video: 'nOgK8hk5nOM', pergunta: [26, 28, 110]},
  {name: 'De onde vem a palavra Capoeira?', video: 'zysQBF0edaY', pergunta: [1, 123, 254]},
  {name: 'A capoeira é respeitada hoje em dia?', video: 'IVzYfJTPr4U', pergunta: [42, 100, 247]},
  {name: 'Quais os benefícios da Capoeira para os mais jovens?', video: 'PXaE5sOamW4', pergunta: [40, 95, 96]},
  {name: 'Dá vontade de desistir por causa do racismo?', video: 'yhlHkavzqs8', pergunta: [222, 232, 271]},
  {name: 'A capoeira tem regras?', video: 'aRjW4mwwD74', pergunta: [43, 27, 245]},
  {name: 'Como é a graduação na capoeira?', video: '3lGKzjmMn4c', pergunta: [21, 37, 131]},
  {name: 'Capoeira é dança ou luta?', video: 'lekMJ9d1nXU', pergunta: [35, 254, 110]},
  {name: 'Quais lições que a capoeira ensina?', video: '_A9qsBd3czk', pergunta: [41, 105, 38]},
  {name: 'É difícil praticar capoeira em São Caetano?', video: 'YHVK2drXUU4', pergunta: [124, 247, 43]},
  {name: 'Como são as músicas de capoeira? ', video: 'fv18y24JXVU', pergunta: [32, 33, 127]},
  {name: 'Como aprendemos as músicas de capoeira?', video: '1wSO6gAjhdI', pergunta: [33, 36, 39]},
  {name: 'Sobre o que falam as músicas da capoeira?', video: 'iZQiMC4b6hw', pergunta: [32, 37, 57]},
  {name: 'Qual o papel do berimbau na capoeira?', video: '-OjxflpyhSQ', pergunta: [128, 31, 36]},
  {name: 'Capoeira é um jogo violento?', video: 'lkdPexG_mkk', pergunta: [37, 98, 245]},
  {name: 'Quais os instrumentos que compõe a roda de capoeira?', video: 'AUGEtMFIw2s', pergunta: [31, 34, 110]},
  {name: 'Qual a idade adequada para praticar capoeira?', video: 'shJcQUlv5S0', pergunta: [29, 38, 24]},
  {name: 'As mulheres têm espaço na capoeira?', video: 'wR10jgVrxcc', pergunta: [24, 253, 206]},
  {name: 'Qual a relação entre Samba, Maculelê e Capoeira?', video: '05hh6KJCGOY', pergunta: [236, 113, 131]},
  {name: 'O que podemos aprender através da capoeira?', video: 'TjPjfWuhA-w', pergunta: [29, 105, 96]},
  {name: 'Dá para viver de capoeira?', video: 'ee0umENYyv8', pergunta: [23, 124, 250]},
  {name: 'Capoeira é coisa de marginal?', video: 'hZ9UIi3cUVE', pergunta: [99, 272, 9]},
  {name: 'Qualquer pessoa pode praticar capoeira?', video: 'm_weS3Lk6Xs', pergunta: [263, 250, 109]},
  {name: 'Cultura Nordestina tem valor?', video: '6o90S067buY', pergunta: [63, 56, 5]},
  {name: 'Como os nordestinos eram recebidos em São Caetano?', video: 'EY8Zayu6hqQ', pergunta: [55, 46, 189]},
  {name: 'Os nordestinos migrantes tentavam preservar a sua cultura?', video: '2S2yX9Zngb8', pergunta: [54, 63, 102]},
  {name: 'Hoje em dia ainda existe muito preconceito?', video: 'Jq7u-L2zTtM', pergunta: [49, 240, 257]},
  {name: 'Quando os nordestinos vieram para São Caetano do Sul?', video: 'XTETFClPB7k', pergunta: [52, 71, 45]},
  {name: 'O branqueamento continua ainda hoje?', video: 'UMn7Y2r-Qto', pergunta: [104, 115, 151]},
  {name: 'Como começou a história oficial de São Caetano?', video: 'CQJq6_RvOqg', pergunta: [60, 49, 12]},
  {name: 'Por que ocultar o passado?', video: 'M-WwMBV4v1U', pergunta: [125, 180, 57]},
  {name: 'Como os nordestinos vieram para cá?', video: 'BfZ9KEoUjak', pergunta: [71, 46, 48]},
  {name: 'Qual a importância de estudar a história?', video: 'mUv_Iase3XU', pergunta: [117, 136, 228]},
  {name: 'De quais estados vieram os nordestinos?', video: '_rybqW9DbAU', pergunta: [45, 229, 189]},
  {name: 'Em quais bairros de São Caetano os nordestinos se instalaram?', video: 'V6RyT23cZQ8', pergunta: [188, 58, 187]},
  {name: 'O que é a Festa Nordestina de São Caetano do Sul?', video: 'fh3nSClR-CU', pergunta: [193, 233, 238]},
  {name: 'Podemos escolher contar outra história?', video: '6odHU3oekDs', pergunta: [65, 117, 60]},
  {name: 'Por que muitos nordestinos saíram de São Caetano?', video: 'mRbnh-dxoS8', pergunta: [91, 77, 280]},
  {name: 'São Caetano tem favela?', video: 'BbCeIxyw9YY', pergunta: [77, 240, 61]},
  {name: 'Como essa narrativa idealizada se sustenta?', video: 'Wj678U955RE', pergunta: [65, 79, 259]},
  {name: 'O que é o higienismo?', video: 'ovJNSUzTjtI', pergunta: [102, 49, 220]},
  {name: 'Quem é o nordestino?', video: 'RM_ov2zfxgE', pergunta: [44, 52, 5]},
  {name: 'Tem mais de uma cultura nordestina?', video: 'p0bbRpIhUpg', pergunta: [16, 111, 177]},
  {name: 'De onde vem o nome São Caetano?', video: 'CeTKalidJcc', pergunta: [80, 83, 85]},
  {name: 'Por que desconstruir essa história tradicional?', video: 'tVhXthms-qg', pergunta: [53, 118, 228]},
  {name: 'Quem vivia na fazenda São Caetano?', video: '_nqe-xUhqlQ', pergunta: [67, 68, 216]},
  {name: 'O que a Fazenda São Caetano produzia?', video: 'DYrwkJXg_5U', pergunta: [68, 80, 210]},
  {name: 'O que aconteceu com os escravos da fazenda?', video: 'H9mFIa0c5lQ', pergunta: [69, 101, 11]},
  {name: 'Por que não tem negros nem índios nos nomes das ruas e dos monumentos da cidade?', video: 'PvhpeFVM0vU', pergunta: [9, 61, 104]},
  {name: 'Como a comunidade negra se organizava em São Caetano?', video: 'MXmGkjwUPto', pergunta: [277, 122, 226]},
  {name: 'Como os nordestinos se estabeleceram em São Caetano?', video: 'V-5WyQ9nd2M', pergunta: [62, 55, 187]},
  {name: 'Como aconteceu o crescimento da cidade?', video: 'YeLiZkhpRTo', pergunta: [73, 208, 88]},
  {name: 'O que foi o movimento autonomista?', video: 'D2UgZfHODu0', pergunta: [75, 78, 273]},
  {name: 'Por que tem um bairro chamado Cerâmica?', video: '9PFrQ2X66bM', pergunta: [191, 76, 196]},
  {name: 'Como aconteceu o movimento autonomista de São Caetano?', video: 'zX2jSrgjL4I', pergunta: [85, 2, 273]},
  {name: 'O que era o Buracão da Cerâmica?', video: 'nOONW90WZkI', pergunta: [196, 77, 61]},
  {name: 'Como as favelas foram retiradas de São Caetano?', video: 'idGRyPT8-9g', pergunta: [88, 213, 240]},
  {name: 'Tem movimentos sociais em São Caetano?', video: 'HFwIfF_WDAM', pergunta: [73, 273, 70]},
  {name: 'Por que São Caetano se diz italiana?', video: '6M-5CQPD61E', pergunta: [254, 173, 59]},
  {name: 'O que foi o Bairro de São Caetano?', video: 'hZcI_cVbBUQ', pergunta: [67, 81, 174]},
  {name: 'Como era a população do Bairro de São Caetano?', video: 'lhOsfeSrJD8', pergunta: [69, 101, 68]},
  {name: 'O trem foi importante para região?', video: 'HRUsoWrc5RY', pergunta: [89, 85, 229]},
  {name: 'Como era a Fazenda de São Caetano?', video: 'bg5OXTxLmAQ', pergunta: [66, 51, 64]},
  {name: 'Como é São Caetano hoje?', video: 'lbSwyIc6Q1I', pergunta: [3, 88, 89]},
  {name: 'Como se deu o desenvolvimento da cidade de São Caetano?', video: 'YHQhz0ODkgk', pergunta: [84, 132, 72]},
  {name: 'Qual a imagem que São Caetano constrói de si?', video: '2XhahUc0Xe4', pergunta: [92, 212, 61]},
  {name: 'A verticalização traz problema à cidade?', video: 'LmSYbGiNXtY', pergunta: [93, 91, 197]},
  {name: 'É verdade que São Caetano não tem favelas?', video: 'gt86DroMsS4', pergunta: [77, 271, 241]},
  {name: 'O transporte público em São Caetano é eficaz?', video: 'gsQRPW8P8hA', pergunta: [90, 94, 82]},
  {name: 'Por que o ABC não tem um transporte público de qualidade?', video: 'FPnQJdjSQeE', pergunta: [72, 190, 152]},
  {name: 'Qual o perfil de habitação em São Caetano hoje?', video: 'SySkueyAXHk', pergunta: [12, 90, 278]},
  {name: 'Tem preconceito de classe em São Caetano?', video: '25gFD34-H1I', pergunta: [207, 86, 49]},
  {name: 'Onde acontece o processo de verticalização?', video: 'Yk7kGLofkMI', pergunta: [87, 89, 132]},
  {name: 'Como podemos melhorar o transporte na cidade?', video: 'fAacj5rF224', pergunta: [280, 90, 82]},
  {name: 'Capoeira ensina respeito?', video: '65fSbxpjBsk', pergunta: [96, 219, 29]},
  {name: 'Como é a educação dos jovens hoje?', video: 'pLikn8qzyU4', pergunta: [105, 24, 97]},
  {name: 'A cultura popular é ensinada nas escolas?', video: 'yZniHeqRwB8', pergunta: [44, 245, 15]},
  {name: 'A capoeira é um esporte de bandido?', video: 'QyccDr_ohUE', pergunta: [99, 114, 220]},
  {name: 'Por que a capoeira é um esporte marginalizado?', video: 'IXfevBYHpqA', pergunta: [216, 115, 108]},
  {name: 'Tem preconceito contra a cultura popular?', video: 'romJ5kqljNA', pergunta: [256, 99, 239]},
  {name: 'Tem cultura indígena e negra em São Caetano?', video: 'zOh4RP-7q4c', pergunta: [7, 11, 102]},
  {name: 'O que significa “embranquecimento”?', video: 'cZf0jcrnnM8', pergunta: [115, 49, 106]},
  {name: 'De onde vem o preconceito?', video: 'q7__Z0CBX3c', pergunta: [112, 20, 248]},
  {name: 'Por que conhecemos poucos negros ilustres?', video: 'pwwjIpf9jns', pergunta: [9, 271, 65]},
  {name: 'Um capoeirista pode ser uma referência?', video: 'qrdPMrjWOZI', pergunta: [95, 29, 265]},
  {name: 'O que é apropriação cultural?', video: 'ygjtFw4n3xU', pergunta: [263, 108, 157]},
  {name: 'O que quer dizer axé?', video: 'WSthLetM9ug', pergunta: [22, 130, 246]},
  {name: 'A cultura negra resiste?', video: 'rqYSb4BUIGo', pergunta: [277, 267, 218]},
  {name: 'Qualquer pessoa pode ser capoeirista?', video: 'QrksyESDCmA', pergunta: [98, 28, 24]},
  {name: 'Como são os ritmos da capoeira?', video: 'xFErVb2e8WY', pergunta: [129, 36, 39]},
  {name: 'O que é o côco?', video: '6a6rpBC6I_k', pergunta: [18, 113, 14]},
  {name: 'Como lidar com uma pessoa racista?', video: 'Pg-OstNmNtY', pergunta: [222, 25, 248]},
  {name: 'Como é um samba de roda?', video: '04pfMODtX1M', pergunta: [107, 39, 111]},
  {name: 'Qual a imagem que a sociedade faz do negro?', video: 'sEPaJ1c8q74', pergunta: [115, 220, 272]},
  {name: 'Por que a presença negra é invisibilizada?', video: 'Lp2_1drDD5E', pergunta: [102, 247, 119]},
  {name: 'Qual a importância da escrita?', video: '_Y8TqSLELVc', pergunta: [118, 228, 117]},
  {name: 'O que a minha história tem de valor?', video: 'FTnpO9eYRmo', pergunta: [6, 121, 120]},
  {name: 'Como a escrita pode ser resistência?', video: 'dumTgQPwyKA', pergunta: [117, 122, 228]},
  {name: 'Tem repressão contra o povo negro?', video: 'mM9Ao782ecI', pergunta: [9, 271, 217]},
  {name: 'Religiosidade é resistência?', video: '_wqNBmAQ2s4', pergunta: [121, 8, 135]},
  {name: 'Qual a importância de lembrar do passado?', video: '-44OUTEWXtU', pergunta: [13, 229, 276]},
  {name: 'A escrita foi ferramenta de resistência dos negros?', video: 'k85kFYZO8fA', pergunta: [70, 118, 108]},
  {name: 'Por que a capoeira foi criada?', video: 'Jd8eVihZyBA', pergunta: [126, 28, 131]},
  {name: 'A capoeira tem espaço em São Caetano?', video: 'bt-0FXyrgBw', pergunta: [19, 226, 274]},
  {name: 'Tem um cemitério indígena e negro em São Caetano?', video: 'sGZLcemgbzs', pergunta: [11, 66, 69]},
  {name: 'De onde vem a capoeira?', video: 'xojfV9Lpb4o', pergunta: [22, 129, 123]},
  {name: 'Como a música afeta a roda de capoeira?', video: 'xE47LA3wWEs', pergunta: [33, 110, 128]},
  {name: 'O que é o berimbau?', video: 'lZVNnYQY0lI', pergunta: [34, 31, 130]},
  {name: 'Qual a diferença entre os ritmos da capoeira?', video: 'b8CdLIu96Ag', pergunta: [39, 60, 131]},
  {name: 'O que é a macumba?', video: '0G7mj4LeWM8', pergunta: [128, 262, 8]},
  {name: 'Quais as manifestações culturais da capoeira?', video: 'PPu7i0LyEtY', pergunta: [31, 39, 113]},
  {name: 'O progresso de São Caetano está alterando a cidade?', video: 'fzSKEU4GEhY', pergunta: [3, 279, 211]},
  {name: 'Quais as dificuldades de uma aldeia indígena?', video: '9mR-ZtTowOI', pergunta: [134, 135, 145]},
  {name: 'Como é a educação indígena?', video: 'KrVQvq1Poww', pergunta: [136, 146, 181]},
  {name: 'Como é a religiosidade indígena?', video: 'PwYhCTvWbQM', pergunta: [184, 154, 149]},
  {name: 'Como aprender sem livros?', video: 'TeNAMQVzNWQ', pergunta: [146, 148, 140]},
  {name: 'Para que o indígena quer terra?', video: 'pt9dZ0AgqiQ', pergunta: [138, 7, 172]},
  {name: 'Onde fica o território Guarani?', video: '-a8msL-0ORU', pergunta: [141, 176, 168]},
  {name: 'Quais nomes remetem à presença indígena?', video: 'dQ4gg8ENWZA', pergunta: [171, 138, 143]},
  {name: 'Por que vocês vivem em aldeias?', video: 'L9vo5i9dKcE', pergunta: [142, 133, 168]},
  {name: 'Os indígenas têm apoio dos governos?', video: 'HKQuNWRvn3s', pergunta: [133, 169, 175]},
  {name: 'Como se faz para ser feliz?', video: 'dGLrzcmp_e0', pergunta: [147, 140, 121]},
  {name: 'Todas as etnias indígenas são iguais?', video: 'EgzDIbtsFhY', pergunta: [176, 179, 180]},
  {name: 'Atualmente quantos indígenas existem no Brasil?', video: 'Q6Kx0lMVMlE', pergunta: [149, 101, 182]},
  {name: 'Como é a saúde indígena?', video: 'ZfLSm9XJdQM', pergunta: [134, 169, 120]},
  {name: 'Como são os contos tradicionais Guarani?', video: 'wIu4UlLuNpw', pergunta: [148, 134, 171]},
  {name: 'O que o indígena pensa sobre a cidade?', video: 'AA6j8P0wGWQ', pergunta: [169, 140, 179]},
  {name: 'Que tipos de histórias os antepassados Guarani contavam?', video: 'AlAukyujTG8', pergunta: [146, 121, 134]},
  {name: 'Como vivem os indígenas?', video: 'OmChXz_lib8', pergunta: [140, 133, 147]},
  {name: 'Quais as dificuldades de ser mãe de santo?', video: 'BKDlTI_jGDU', pergunta: [153, 158, 0]},
  {name: 'Tem muitos negros em São Caetano?', video: 'rm4T-5XD3Ag', pergunta: [214, 215, 165]},
  {name: 'A cidade mudou muito nos últimos anos?', video: 'fGtQ1DuFDaI', pergunta: [153, 91, 198]},
  {name: 'Por que as religiões afro são mal vistas em São Caetano?', video: 'JLlSXMeOMrM', pergunta: [160, 162, 223]},
  {name: 'Como o preconceito se reflete na religião?', video: 'KItvuIkosog', pergunta: [162, 221, 261]},
  {name: 'Como se sustenta o trabalho social do terreiro?', video: 'ozGOVw2-ssc', pergunta: [156, 164, 221]},
  {name: 'Tem outros terreiros que resistem em São Caetano?', video: '6o72zYEPsWA', pergunta: [155, 161, 224]},
  {name: 'Religiões de matriz africana sofrem apropriação cultural?', video: 'zaVQFx_Gkng', pergunta: [164, 106, 227]},
  {name: 'É possível enfrentar o preconceito contra as religiões de matriz africana?', video: 'YkuUOiUy5CE', pergunta: [154, 167, 163]},
  {name: 'Religião de matriz africana cultua as imagens de santos?', video: 'YbNqFb_CrR4', pergunta: [160, 150, 223]},
  {name: 'Religião de matriz africana cultua demônios?', video: 'SDs47xAn0Fw', pergunta: [163, 159, 167]},
  {name: 'Qual é a melhor Religião matriz africana?', video: 'gbMYlXjtyLo', pergunta: [162, 157, 215]},
  {name: 'Toda religião de matriz africana é igualmente discriminada?', video: 'udDazs1CtmQ', pergunta: [163, 167, 225]},
  {name: 'O que é o Exu?', video: 'v3sdBUfE0Tg', pergunta: [223, 158, 154]},
  {name: 'Brancos podem cultuar religiões de matriz africana?', video: 'xvZs3UhR89o', pergunta: [165, 151, 248]},
  {name: 'Quem cultua religião de matriz africana também sofre racismo?', video: 'ourWLu2unFs', pergunta: [164, 222, 220]},
  {name: 'O que foi o projeto João de Barro?', video: 'pMrITlHpCo4', pergunta: [278, 91, 152]},
  {name: 'Quem cultua Religião de matriz africana é espírita?', video: 'tLLaafVqJ0Q', pergunta: [159, 157, 223]},
  {name: 'Indígenas podem viver na cidade?', video: 'iSeMd8kgUjU', pergunta: [169, 7, 147]},
  {name: 'Por que o indígena veio para a cidade?', video: 'cu6V6Z1pUQ8', pergunta: [170, 178, 147]},
  {name: 'Como é a vida de um indígena urbano?', video: 'BHFYQ4prc4I', pergunta: [182, 178, 204]},
  {name: 'Por onde passava o caminho da “terra sem males”?', video: 'G4MKRlHmWus', pergunta: [172, 176, 139]},
  {name: 'São Caetano era um território indígena?', video: 'PswpiKFHJ4s', pergunta: [176, 181, 137]},
  {name: 'Por que os italianos vieram para cá?', video: '1qC7VFSUIJ0', pergunta: [69, 174, 102]},
  {name: 'Já tinha gente em São Caetano antes da fazenda beneditina?', video: 'hlwZK8Ulf3M', pergunta: [83, 79, 172]},
  {name: 'Os indígenas resistiram à colonização?', video: 'OQNg2XXVEMs', pergunta: [180, 181, 10]},
  {name: 'Quais povos indígenas habitavam essa região?', video: 'X9-8UsEt2Iw', pergunta: [171, 179, 144]},
  {name: 'Os nordestinos chegaram em São Caetano com a industrialização?', video: 'hziw3iu58tw', pergunta: [52, 58, 85]},
  {name: 'Por que é raro conhecermos indígenas na cidade?', video: 'dG8RxgBtUiE', pergunta: [170, 205, 183]},
  {name: 'Quais povos indígenas vivem hoje em São Caetano?', video: 'i7CUpjrVd7w', pergunta: [185, 133, 180]},
  {name: 'Os indígenas são muito invisibilizados na história do Brasil?', video: 'DLOLGMhIzt8', pergunta: [181, 50, 139]},
  {name: 'Para que conhecer a história indígena?', video: '2bXwWMVh_7A', pergunta: [143, 2, 184]},
  {name: 'Quais povos indígenas vivem hoje na região do ABC?', video: '01Vsza7MqoE', pergunta: [138, 149, 185]},
  {name: 'A mulher indígena sofre muito preconceito?', video: '6M731B42le4', pergunta: [178, 144, 205]},
  {name: 'Todo ritual indígena é xamanista?', video: '6mk4NNJmGzM', pergunta: [135, 101, 154]},
  {name: 'É importante realizar o autorreconhecimento?', video: 'x7shEiPZB-M', pergunta: [270, 204, 180]},
  {name: 'Tem emprego em São Caetano?', video: 'hkApGgxoR5E', pergunta: [199, 230, 208]},
  {name: 'Tem preconceito de bairro em São Caetano?', video: '7rBLqCs6Qwg', pergunta: [12, 240, 206]},
  {name: 'Tem acolhimento para os nordestinos hoje?', video: 'CuNh-B0YFc8', pergunta: [189, 45, 230]},
  {name: 'Ainda vem muitos nordestinos para São Caetano?', video: 'lPDkrQ1Baac', pergunta: [188, 186, 193]},
  {name: 'São Caetano é uma cidade cara?', video: '-dJRNgO0Dnc', pergunta: [88, 93, 191]},
  {name: 'A construção do shopping melhorou o Bairro Cerâmica?', video: 'FgXH0WVf9ds', pergunta: [74, 76, 190]},
  {name: 'Tinha cultura popular antigamente em São Caetano?', video: 'QCmpEorL2ys', pergunta: [97, 243, 260]},
  {name: 'Como é a Festa Nordestina de São Caetano?', video: 'YVzwdC_gHhY', pergunta: [14, 17, 18]},
  {name: 'Todo nordestino gosta de comida nordestina?', video: 'DAMTTR1C8G0', pergunta: [44, 5, 233]},
  {name: 'Como era a infância antigamente em São Caetano?', video: 'V-7GsMXl1D0', pergunta: [2, 197, 198]},
  {name: 'Como era o buracão da cerâmica?', video: 'ln_afTTXubM', pergunta: [195, 74, 200]},
  {name: 'Mudou muita coisa na cidade nos últimos anos?', video: 'WO0CS7Cx8EY', pergunta: [198, 211, 200]},
  {name: 'Por que São Caetano mudou tanto?', video: '77BbIU6M-B8', pergunta: [199, 210, 192]},
  {name: 'Antigamente tinha mais empregos?', video: 'we84LX5HUd4', pergunta: [200, 230, 208]},
  {name: 'Muitas fábricas fecharam em São Caetano?', video: 'qrIe6ttUmmw', pergunta: [199, 231, 209]},
  {name: 'O cenário urbano mudou muito hoje em dia?', video: 'kT_LIkP56H4', pergunta: [210, 202, 203]},
  {name: 'A convivência com os vizinhos era diferente antigamente?', video: 'u1LrjwM-vVI', pergunta: [152, 234, 91]},
  {name: 'No passado tinha muita cultura negra na cidade?', video: 'uaglPKJk3lg', pergunta: [267, 108, 234]},
  {name: 'É fácil se autoidentificar indígena?', video: '0uV0QkuITrs', pergunta: [205, 183, 270]},
  {name: 'O que você sabe da sua ascendência indígena?', video: 'Bm86d1b3hcc', pergunta: [204, 274, 7]},
  {name: 'Tem preconceito de gênero em São Caetano?', video: '8SVv4ldnERI', pergunta: [9, 153, 207]},
  {name: 'Como o preconceito se manifesta em São Caetano?', video: 'MKfZBejpkX4', pergunta: [206, 187, 92]},
  {name: 'Como eram as condições de trabalho nas fábricas de São Caetano?', video: 'H3EpYVovrL8', pergunta: [231, 186, 209]},
  {name: 'Por que a antiga fábrica da Matarazzo tem o solo contaminado?', video: 'N7k3i9PGJF4', pergunta: [279, 211, 231]},
  {name: 'Antigamente tinha muitos rios em São Caetano?', video: 'Bs0cft-suJA', pergunta: [211, 172, 201]},
  {name: 'O progresso da cidade alterou muito o cenário urbano?', video: 'z4ffx1ZThjs', pergunta: [212, 210, 195]},
  {name: 'Antigamente tinha muitos cortiços em São Caetano?', video: 'SgmeHlKV_Vw', pergunta: [213, 59, 278]},
  {name: 'Os antigos moradores de cortiço foram expulsos de São Caetano?', video: 'PCnY4rxKHBw', pergunta: [77, 212, 280]},
  {name: 'Qual a origem dos negros de São Caetano?', video: '6uslVgKnXG0', pergunta: [216, 241, 151]},
  {name: 'Como é a cultura afro-brasileira?', video: 'xIEtL1PNa1c', pergunta: [217, 11, 218]},
  {name: 'Por que os negros foram escravizados?', video: 'yMElBq4T86w', pergunta: [217, 108, 257]},
  {name: 'Todos os negros escravizados eram tratados de forma igual?', video: 'zG1SIRvqTL4', pergunta: [220, 119, 232]},
  {name: 'A forma de se vestir também é cultura?', video: '9OXsMek_WaE', pergunta: [224, 215, 8]},
  {name: 'Por que reverenciar os antepassados?', video: 'FoXPpdkYFi8', pergunta: [221, 117, 225]},
  {name: 'Por que os negros recebem tantos rótulos negativos?', video: 'bnIetvFLkU0', pergunta: [104, 272, 102]},
  {name: 'Por que ter o Candomblé como referência?', video: 'yTtTy3AxLps', pergunta: [219, 225, 8]},
  {name: 'Os negros também podem ser racistas?', video: '6WYvSthDJfs', pergunta: [248, 227, 226]},
  {name: 'Religiões Afro cultuam os elementos da natureza?', video: 'LpW9kauaOF0', pergunta: [163, 167, 225]},
  {name: 'O que simbolizam as roupas do Candomblé?', video: '_t_xiWDTLbQ', pergunta: [218, 157, 154]},
  {name: 'O que simbolizam os paramentos do Candomblé?', video: 'OsPS4h2jbtQ', pergunta: [221, 160, 262]},
  {name: 'A cultura negra é aceita em São Caetano?', video: 'cBYfDM-Fr6o', pergunta: [236, 187, 275]},
  {name: 'Qualquer pessoa pode falar sobre raça?', video: 'aMt4qFXn91w', pergunta: [9, 248, 164]},
  {name: 'Por que a educação é importante?', video: 'rvtymaHBElA', pergunta: [218, 183, 258]},
  {name: 'Como era a vinda de um nordestino?', video: 'I-mqS_foKrc', pergunta: [52, 82, 230]},
  {name: 'Como que era para procurar emprego antigamente?', video: 'BUEaCweMVXE', pergunta: [199, 231, 208]},
  {name: 'Antigamente tinha outros trabalhos que não nas fábricas?', video: 'uUOqO4PCETs', pergunta: [199, 234, 120]},
  {name: 'Como conviver com o racismo?', video: 'uBMKoz0UO9Q', pergunta: [271, 0, 47]},
  {name: 'Os nordestinos faziam muitas festas?', video: 'JPoqX2fvRBA', pergunta: [234, 212, 56]},
  {name: 'Antigamente tinha solidariedade entre os negros em São Caetano?', video: 'V-bxD1h8_tY', pergunta: [230, 45, 119]},
  {name: 'Mudou muita coisa na cidade?', video: 'w1kyJ1dPbys', pergunta: [72, 198, 3]},
  {name: 'Por que fazer samba?', video: 'IwddXb4ZZF8', pergunta: [258, 238, 237]},
  {name: 'Como se faz uma festa na rua?', video: '26vXI8RY-ek', pergunta: [236, 252, 70]},
  {name: 'Como se organiza uma festa autônoma?', video: 'Kv1u7-IQuog', pergunta: [240, 17, 234]},
  {name: 'Os sambistas sofrem discriminação?', video: 'rP0kBsFqr04', pergunta: [0, 19, 240]},
  {name: 'As pessoas discriminam as comunidades?', video: 'AymBIjGNWsU', pergunta: [241, 187, 59]},
  {name: 'Quais os bairros com mais negros em São Caetano?', video: 'FraVw_MnNWc', pergunta: [214, 71, 11]},
  {name: 'Como mora a população pobre de São Caetano?', video: 'DTVtR4eRyn0', pergunta: [166, 278, 59]},
  {name: 'Cultura popular tem valor?', video: 'Cf7LEEFfI2c', pergunta: [4, 164, 251]},
  {name: 'O que é a capoeira?', video: 'EHy5yaqLfkE', pergunta: [245, 123, 26]},
  {name: 'A capoeira é um jogo perigoso?', video: 'C4XlA49jth8', pergunta: [35, 266, 43]},
  {name: 'O que é mandinga?', video: 'c-2J7GVf9M8', pergunta: [130, 262, 42]},
  {name: 'Como combater o preconceito contra a capoeira?', video: 'DZyxTO-Pp24', pergunta: [253, 99, 100]},
  {name: 'Qual a diferença entre racismo e preconceito?', video: 'jNK_uvawu24', pergunta: [222, 271, 227]},
  {name: 'São Caetano valoriza a cultura popular?', video: 'zUfWGv9hpl4', pergunta: [252, 97, 251]},
  {name: 'Capoeira é religião?', video: '2kylj4n6kDQ', pergunta: [130, 33, 154]},
  {name: 'O que é o Conselho Municipal de Cultura?', video: '97qLiI-m5po', pergunta: [252, 273, 29]},
  {name: 'Por que a prefeitura não proporciona mais incentivos à cultura popular?', video: 'rX3La6UtENg', pergunta: [255, 256, 4]},
  {name: 'O que a capoeira pode mudar na vida de uma pessoa?', video: 'm-dO98Kge-0', pergunta: [40, 244, 105]},
  {name: 'Quais manifestações culturais se relacionam com a capoeira?', video: 'Ghj5kuIHlZs', pergunta: [39, 110, 111]},
  {name: 'Tem maracatu em São Caetano?', video: 'QOwSAIC_R-c', pergunta: [113, 111, 226]},
  {name: 'Como combater o preconceito contra a cultura popular?', video: 'sjWt0Jsql8w', pergunta: [243, 239, 268]},
  {name: 'Ainda existe racismo no Brasil?', video: 'kAuCifWo7sA', pergunta: [222, 272, 93]},
  {name: 'Para que serve a educação?', video: 'w1rXP1IKt-k', pergunta: [257, 228, 116]},
  {name: 'A raiz cultural de São Caetano não é europeia?', video: 'APj4PeE4-0s', pergunta: [115, 101, 275]},
  {name: 'Como a cultura popular sobrevive?', video: '31kf8xCQAlk', pergunta: [265, 249, 10]},
  {name: 'Por que as religiões afro-brasileiras são tão discriminadas?', video: 'sQi-ikHwv2U', pergunta: [162, 250, 246]},
  {name: 'Religião de matriz africana é macumba?', video: 't97fHbvGd0U', pergunta: [130, 261, 184]},
  {name: 'Por que a cultura popular brasileira tem relação com as culturas africanas?', video: 'ExHaMVKUk8w', pergunta: [264, 145, 267]},
  {name: 'A capoeira é africana?', video: 'iOu13WZhVlA', pergunta: [22, 126, 103]},
  {name: 'Como alguém se torna um mestre na cultura popular?', video: '8dq1qjoAEpA', pergunta: [105, 27, 18]},
  {name: 'Por que a capoeira era proibida?', video: 'rx6tqCvyY4I', pergunta: [98, 35, 78]},
  {name: 'Qual a relação entre grafiti e cultura negra?', video: 'FdTaBwCZWc0', pergunta: [268, 269, 243]},
  {name: 'Qual a diferença entre grafiti e pichação?', video: 'zK9xhy6vHzM', pergunta: [267, 100, 269]},
  {name: 'Por que fazer grafiti?', video: 'qGBCvMEpxGg', pergunta: [268, 267, 238]},
  {name: 'É importante realizar o autorreconhecimento?', video: '9qXEeREQd_8', pergunta: [185, 204, 274]},
  {name: 'É possível enfrentar o racismo?', video: 'eWxBB6sPRSQ', pergunta: [122, 232, 257]},
  {name: 'Por que o povo negro é mais pobre?', video: 'r5yKDMAJRO0', pergunta: [216, 217, 68]},
  {name: 'Para que servem os movimentos sociais?', video: 'dq6JPd5Swxo', pergunta: [78, 10, 94]},
  {name: 'Como realizar o autorreconhecimento?', video: 'x03apDoPDFs', pergunta: [270, 204, 62]},
  {name: 'Onde está a cultura negra?', video: 'evPKLZYlEMs', pergunta: [203, 215, 106]},
  {name: 'Qual foi o primeiro terreiro de matriz africana em São Caetano?', video: 'w2-PchRYHrs', pergunta: [158, 8, 221]},
  {name: 'O que foi o clube Luiz Gama?', video: 'fYCqLRDD_8I', pergunta: [70, 122, 234]},
  {name: 'Tem moradia popular em São Caetano?', video: 'IoZ50Dt_xeM', pergunta: [242, 263, 212]},
  {name: 'O terreno da antiga fábrica da Matarazzo está condenado?', video: 'wGSq_fa9MZQ', pergunta: [209, 3, 200]},
  {name: 'É possível mudar a cidade sem expulsar a população local?', video: 'B6yLoCfSHVM', pergunta: [166, 84, 273]}
];
