var mapaDeNavegacao = [
  {name: "Tem discriminação em São Caetano?", video: "MI8U5rQXUQs", pergunta: [101, 227, 93]},
  {name: "Tem capoeria em São Caetano?", video: "3YbOkb5Sxi0", pergunta: [245, 29, 265]},
  {name: "Tem história em São Caetano?", video: "hHu1FwaooEs", pergunta: [54, 67, 86]},
  {name: "Tem verticalização em São Caetano?", video: "OjNVNLGH2kU", pergunta: [94, 88, 280]},
  {name: "Tem cultura popular em São Caetano?", video: "scAman4qeXo", pergunta: [250, 101, 98]},
  {name: "Tem nordestinos em São Caetano?", video: "xXkBuvDV3ng", pergunta: [72, 49, 230]},
  {name: "Tem memória em São Caetano?", video: "hTffqEO37pQ", pergunta: [122, 102, 236]},
  {name: "Tem presença indígena em São Caetano?", video: "aG9e8L5rtgw", pergunta: [145, 150, 169]},
  {name: "Tem religiões afro em São Caetano?", video: "fRyxu2GBXc0", pergunta: [151, 161, 277]},
  {name: "Tem racismo em São Caetano?", video: "32iuclrqm9A", pergunta: [216, 249, 221]},
  {name: "Tem resistência em São Caetano?", video: "6P-umSJgVlQ", pergunta: [109, 261, 238]},
  {name: "Tem negritude em São Caetano?", video: "d7ZreTV_lNo", pergunta: [276, 67, 175]},
  {name: "Como se imagina que é a população de São Caetano?", video: "j1vZYKoDvKg", pergunta: [14, 87, 66]},
  {name: "Como São Caetano representa a sua memória?", video: "S_aodABI058", pergunta: [58, 70, 7]},
  {name: "Como é a festa junina no nordeste?", video: "3G5XEt_9ROE", pergunta: [16, 64, 18]},
  {name: "A cultura nordestina é respeitada na escola?", video: "IXgdUCnZzu0", pergunta: [15, 45, 98]},
  {name: "Como é a fogueira das viúvas?", video: "hlwZK8Ulf3M", pergunta: [15, 6, 194]},
  {name: "Como é a comida nordestina?", video: "dg7ecygyIlA", pergunta: [195, 63, 16]},
  {name: "Como é o reizado?", video: "bWDZb1g-4sc", pergunta: [17, 112, 5]},
  {name: "Tem preconceito com a pratica da capoeira?", video: "lxTwvKxq6WY", pergunta: [100, 31, 227]},
  {name: "Dá pra reconhecer quem tem preconceito?", video: "4EcUJUVbOio", pergunta: [26, 104, 113]},
  {name: "Quais os tipos de capoeira?", video: "nOgK8hk5nOM", pergunta: [27, 29, 111]},
  {name: "De onde vem a palavra Capoeira?", video: "zysQBF0edaY", pergunta: [2, 124, 255]},
  {name: "A capoeira é respeitada hoje em dia?", video: "IVzYfJTPr4U", pergunta: [43, 101, 248]},
  {name: "Quais os benefícios da Capoeira para os mais jovens?", video: "PXaE5sOamW4", pergunta: [41, 96, 97]},
  {name: "Dá vontade de desistir por causa do racismo?", video: "yhlHkavzqs8", pergunta: [223, 233, 272]},
  {name: "A capoeira tem regras?", video: "aRjW4mwwD74", pergunta: [44, 28, 246]},
  {name: "Como é a graduação na capoeira?", video: "3lGKzjmMn4c", pergunta: [22, 38, 132]},
  {name: "Capoeira é dança ou luta?", video: "lekMJ9d1nXU", pergunta: [36, 255, 111]},
  {name: "Qual lições que a capoeira ensina?", video: "_A9qsBd3czk", pergunta: [42, 106, 39]},
  {name: "É dificil praticar capoeira em São Caetano?", video: "YHVK2drXUU4", pergunta: [125, 248, 44]},
  {name: "Como são as músicas de capoeira? ", video: "fv18y24JXVU", pergunta: [33, 34, 128]},
  {name: "Como aprendemos musicas de capoeira?", video: "1wSO6gAjhdI", pergunta: [34, 37, 40]},
  {name: "Sobre o que falam as músicas da capoeira?", video: "iZQiMC4b6hw", pergunta: [33, 38, 58]},
  {name: "Qual o papel do berimbau na capoeira?", video: "-OjxflpyhSQ", pergunta: [129, 32, 37]},
  {name: "Capoeira é um jogo violento?", video: "lkdPexG_mkk", pergunta: [38, 99, 246]},
  {name: "Quais os instrumentos que compõe a roda de capoeira?", video: "AUGEtMFIw2s", pergunta: [32, 35, 111]},
  {name: "Qual a idade adequada para praticar capoeira?", video: "shJcQUlv5S0", pergunta: [30, 39, 25]},
  {name: "As mulheres tem espaço na capoeira?", video: "wR10jgVrxcc", pergunta: [25, 254, 207]},
  {name: "Qual a relação entre Samba, Macululê e Capoeira?", video: "05hh6KJCGOY", pergunta: [237, 114, 132]},
  {name: "O que podemos aprender através da capoeira?", video: "TjPjfWuhA-w", pergunta: [30, 106, 97]},
  {name: "Dá pra viver de capoeira?", video: "ee0umENYyv8", pergunta: [24, 125, 251]},
  {name: "Capoeira é coisa de marginal?", video: "hZ9UIi3cUVE", pergunta: [100, 273, 10]},
  {name: "Qualquer pessoa pode praticar capoeira?", video: "m_weS3Lk6Xs", pergunta: [264, 251, 110]},
  {name: "Cultura Nordestina tem valor?", video: "6o90S067buY", pergunta: [64, 57, 6]},
  {name: "Como os nordestinos eram recebidos em São Caetano?", video: "EY8Zayu6hqQ", pergunta: [56, 47, 190]},
  {name: "Os nordestinos migrantes tentavam preservar sua cultura?", video: "2S2yX9Zngb8", pergunta: [55, 64, 103]},
  {name: "Hoje em dia ainda existe muito preconceito?", video: "Jq7u-L2zTtM", pergunta: [50, 241, 258]},
  {name: "Quando os nordestinos vieram pra SCS?", video: "XTETFClPB7k", pergunta: [53, 72, 46]},
  {name: "O branqueamento continua ainda hoje?", video: "UMn7Y2r-Qto", pergunta: [105, 116, 152]},
  {name: "Como começou a história oficial de São Caetano?", video: "CQJq6_RvOqg", pergunta: [61, 50, 13]},
  {name: "Por que ocultar o passado?", video: "M-WwMBV4v1U", pergunta: [126, 181, 58]},
  {name: "Como os nordestinos vieram pra cá?", video: "BfZ9KEoUjak", pergunta: [72, 47, 49]},
  {name: "Qual a importância de estudar da história?", video: "mUv_Iase3XU", pergunta: [118, 137, 229]},
  {name: "De quais estados vieram os nordestinos?", video: "_rybqW9DbAU", pergunta: [46, 230, 190]},
  {name: "Em quais bairros de São Caetanoos nordestinos de instalaram?", video: "V6RyT23cZQ8", pergunta: [189, 59, 188]},
  {name: "O que é a festa Nordestina?", video: "fh3nSClR-CU", pergunta: [194, 234, 239]},
  {name: "Podemos escolher contar outra história?", video: "6odHU3oekDs", pergunta: [66, 118, 61]},
  {name: "Por que muitos nordestinos sairam de São Caetano?", video: "mRbnh-dxoS8", pergunta: [92, 78, 281]},
  {name: "São Caetano tem favela?", video: "BbCeIxyw9YY", pergunta: [78, 241, 62]},
  {name: "Como essa narrativa idealizada se sustenta?", video: "Wj678U955RE", pergunta: [66, 80, 260]},
  {name: "O que é o higienismo?", video: "ovJNSUzTjtI", pergunta: [103, 50, 221]},
  {name: "Quem é o nordestino?", video: "RM_ov2zfxgE", pergunta: [45, 53, 6]},
  {name: "Tem mais de uma cultura nordestina?", video: "p0bbRpIhUpg", pergunta: [17, 112, 178]},
  {name: "De onde vem o nome São Caetano?", video: "CeTKalidJcc", pergunta: [81, 84, 86]},
  {name: "Por que desconstruir essa história tradicional?", video: "tVhXthms-qg", pergunta: [54, 119, 229]},
  {name: "Quam vivia na fazenda São Caetano?", video: "_nqe-xUhqlQ", pergunta: [68, 69, 217]},
  {name: "O que a fazenda São Caetano produzia?", video: "DYrwkJXg_5U", pergunta: [69, 81, 211]},
  {name: "O que aconteceu com os escravos da fazenda?", video: "H9mFIa0c5lQ", pergunta: [70, 102, 12]},
  {name: "Por que o nome das ruas e os monumentos da cidade não tem negros nem índios?", video: "PvhpeFVM0vU", pergunta: [10, 62, 105]},
  {name: "Como a comunidade negra se organizava em São Caetano?", video: "MXmGkjwUPto", pergunta: [278, 123, 227]},
  {name: "Como os nordestinos se estabeleceram em São Caetano?", video: "V-5WyQ9nd2M", pergunta: [63, 56, 188]},
  {name: "Como aconteceu o crescimento da cidade?", video: "YeLiZkhpRTo", pergunta: [74, 209, 89]},
  {name: "O que foi o movimento autonomista?", video: "D2UgZfHODu0", pergunta: [76, 79, 274]},
  {name: "Por que tem um bairro chamado Cerâmica?", video: "9PFrQ2X66bM", pergunta: [192, 77, 197]},
  {name: "Como aconteceu o movimento autonomista de São Caetano?", video: "zX2jSrgjL4I", pergunta: [86, 3, 274]},
  {name: "O que era o Buracão da Ceramica?", video: "nOONW90WZkI", pergunta: [197, 78, 62]},
  {name: "Como as favelas foram retiradas de São Caertano?", video: "idGRyPT8-9g", pergunta: [89, 214, 241]},
  {name: "Tem movimentos sociais em São Caetano?", video: "HFwIfF_WDAM", pergunta: [74, 274, 71]},
  {name: "Por que São Caetano se diz italiana?", video: "6M-5CQPD61E", pergunta: [255, 174, 60]},
  {name: "O que foi o Bairro de São Caetano?", video: "hZcI_cVbBUQ", pergunta: [68, 82, 175]},
  {name: "Como era a população do Bairro de São Caetano?", video: "lhOsfeSrJD8", pergunta: [70, 102, 69]},
  {name: "O trem foi importrante pra região?", video: "HRUsoWrc5RY", pergunta: [90, 86, 230]},
  {name: "Como era a fazenda de São Caetano?", video: "bg5OXTxLmAQ", pergunta: [67, 52, 65]},
  {name: "Como é São Caetano hoje?", video: "lbSwyIc6Q1I", pergunta: [4, 89, 90]},
  {name: "Como se deu o desenvolvimento da cidade de São Caetano?", video: "YHQhz0ODkgk", pergunta: [85, 133, 73]},
  {name: "Qual a imagem que São Caetano constrói de si?", video: "2XhahUc0Xe4", pergunta: [93, 213, 62]},
  {name: "A verticalização traz problema à cidade?", video: "LmSYbGiNXtY", pergunta: [94, 92, 198]},
  {name: "É verdade que São Caetano não tem favelas?", video: "gt86DroMsS4", pergunta: [78, 272, 242]},
  {name: "O transporte público em São Caetano é eficaz?", video: "gsQRPW8P8hA", pergunta: [91, 95, 83]},
  {name: "Por que o ABC não tem um transporte público de qualidade?", video: "FPnQJdjSQeE", pergunta: [73, 191, 153]},
  {name: "Qual o perfil de habitação em São Caetano hoje?", video: "SySkueyAXHk", pergunta: [13, 91, 279]},
  {name: "Tem poreconceito de classe em São Caetano?", video: "25gFD34-H1I", pergunta: [208, 87, 50]},
  {name: "Onde acontece o processo de verticalização?", video: "Yk7kGLofkMI", pergunta: [88, 90, 133]},
  {name: "Como podemos melhorar o transporte na cidade?", video: "fAacj5rF224", pergunta: [281, 91, 83]},
  {name: "Capoeira ensina respeito?", video: "65fSbxpjBsk", pergunta: [97, 220, 30]},
  {name: "Como é a educação dos jovens hoje?", video: "pLikn8qzyU4", pergunta: [106, 25, 98]},
  {name: "A cultura popular é ensinada nas escolas?", video: "yZniHeqRwB8", pergunta: [45, 246, 16]},
  {name: "A capoeira é um esporte de bandido?", video: "QyccDr_ohUE", pergunta: [100, 115, 221]},
  {name: "Por que a capoeira é um esporte marginalizado?", video: "IXfevBYHpqA", pergunta: [217, 116, 109]},
  {name: "Tem preconceito contra a cultura popular?", video: "romJ5kqljNA", pergunta: [257, 100, 240]},
  {name: "Tem cultura indígena e negra em São Caetano?", video: "zOh4RP-7q4c", pergunta: [8, 12, 103]},
  {name: "O que significa embranquecimento?", video: "cZf0jcrnnM8", pergunta: [116, 50, 107]},
  {name: "De onde vem o preconceito?", video: "q7__Z0CBX3c", pergunta: [113, 21, 249]},
  {name: "Por que conhecemos poucos negros ilustres?", video: "pwwjIpf9jns", pergunta: [10, 272, 66]},
  {name: "Um capoeirista pode ser uma referência?", video: "qrdPMrjWOZI", pergunta: [96, 30, 266]},
  {name: "O que é apropriação cultural?", video: "ygjtFw4n3xU", pergunta: [264, 109, 158]},
  {name: "O que quer dizer axé?", video: "WSthLetM9ug", pergunta: [23, 131, 247]},
  {name: "A cultura negra resiste?", video: "rqYSb4BUIGo", pergunta: [278, 268, 219]},
  {name: "Qualquer pessoa pode ser capoeirista?", video: "QrksyESDCmA", pergunta: [99, 29, 25]},
  {name: "Como são os ritmos da capoeira?", video: "xFErVb2e8WY", pergunta: [130, 37, 40]},
  {name: "O que é o côco?", video: "6a6rpBC6I_k", pergunta: [19, 114, 15]},
  {name: "Como lidar com uma pessoa racista?", video: "Pg-OstNmNtY", pergunta: [223, 26, 249]},
  {name: "Como é um samba de roda?", video: "04pfMODtX1M", pergunta: [108, 40, 112]},
  {name: "Qual a imagem do negro da sociedade?", video: "sEPaJ1c8q74", pergunta: [116, 221, 273]},
  {name: "Por que a presença negra é invisibilizada?", video: "Lp2_1drDD5E", pergunta: [103, 248, 120]},
  {name: "Qual a importância da escrita?", video: "_Y8TqSLELVc", pergunta: [119, 229, 118]},
  {name: "O que tem a minha história de valor?", video: "FTnpO9eYRmo", pergunta: [7, 122, 121]},
  {name: "Como a escrita pode ser resistência?", video: "dumTgQPwyKA", pergunta: [118, 123, 229]},
  {name: "Tem repressão contra o povo negro?", video: "mM9Ao782ecI", pergunta: [10, 272, 218]},
  {name: "Religiosidade é resistência?", video: "_wqNBmAQ2s4", pergunta: [122, 9, 136]},
  {name: "Qual a importância de lembrar do passado?", video: "-44OUTEWXtU", pergunta: [14, 230, 277]},
  {name: "A escrita foi ferramenta de resistência dos negros?", video: "k85kFYZO8fA", pergunta: [71, 119, 109]},
  {name: "Por que a capoeira foi criada?", video: "Jd8eVihZyBA", pergunta: [127, 29, 132]},
  {name: "A capoeira tem espaço em São Caetano?", video: "bt-0FXyrgBw", pergunta: [20, 227, 275]},
  {name: "Tem um cemitério indígena e negro em São Caetano?", video: "sGZLcemgbzs", pergunta: [12, 67, 70]},
  {name: "De onde vem a capoeira?", video: "xojfV9Lpb4o", pergunta: [23, 130, 124]},
  {name: "Como a música afeta a roda de capoeira?", video: "xE47LA3wWEs", pergunta: [34, 111, 129]},
  {name: "O que é o berimbau?", video: "lZVNnYQY0lI", pergunta: [35, 32, 131]},
  {name: "Qual a diferença entre os ritmos da capoeira?", video: "b8CdLIu96Ag", pergunta: [40, 61, 132]},
  {name: "O que é a macumba?", video: "0G7mj4LeWM8", pergunta: [129, 263, 9]},
  {name: "Quais as manifestações culturais da capoeira?", video: "PPu7i0LyEtY", pergunta: [32, 40, 114]},
  {name: "O progresso de São Caetano está alterando a cidade?", video: "fzSKEU4GEhY", pergunta: [4, 280, 212]},
  {name: "Quais as dificuldades de uma aldeia indígena?", video: "9mR-ZtTowOI", pergunta: [135, 136, 146]},
  {name: "Como é a educação indígena?", video: "KrVQvq1Poww", pergunta: [137, 147, 182]},
  {name: "Como é a religião indígena?", video: "PwYhCTvWbQM", pergunta: [185, 155, 150]},
  {name: "Como aprender sem livros?", video: "TeNAMQVzNWQ", pergunta: [147, 149, 141]},
  {name: "Pra que o indigena quer terra?", video: "pt9dZ0AgqiQ", pergunta: [139, 8, 173]},
  {name: "Onde fica o território Guarany?", video: "-a8msL-0ORU", pergunta: [142, 177, 169]},
  {name: "Quais nomes remetem à presença indígena?", video: "dQ4gg8ENWZA", pergunta: [172, 139, 144]},
  {name: "Por que vocês vivem em aldeias?", video: "L9vo5i9dKcE", pergunta: [143, 134, 169]},
  {name: "Os indígenas têm apoio dos governos?", video: "HKQuNWRvn3s", pergunta: [134, 170, 176]},
  {name: "Como faz pra ser feliz?", video: "dGLrzcmp_e0", pergunta: [148, 141, 122]},
  {name: "Todas as etnias indígenas são iguais?", video: "EgzDIbtsFhY", pergunta: [177, 180, 181]},
  {name: "Atualmente quantos indígenas existem no Brasil?", video: "Q6Kx0lMVMlE", pergunta: [150, 102, 183]},
  {name: "Como é a saúde indígena?", video: "ZfLSm9XJdQM", pergunta: [135, 170, 121]},
  {name: "Como são os contos tradicionais Guarany?", video: "wIu4UlLuNpw", pergunta: [149, 135, 172]},
  {name: "O que o indígena pensa sobre a cidade?", video: "AA6j8P0wGWQ", pergunta: [170, 141, 180]},
  {name: "Que tipos de histórias os antepassados Guarany contavam?", video: "AlAukyujTG8", pergunta: [147, 122, 135]},
  {name: "Como vivem os indígenas?", video: "OmChXz_lib8", pergunta: [141, 134, 148]},
  {name: "Quais dificuldades de ser mãe de santo?", video: "BKDlTI_jGDU", pergunta: [154, 159, 1]},
  {name: "Tem muitos negros em São Caetano?", video: "rm4T-5XD3Ag", pergunta: [215, 216, 166]},
  {name: "A cidade mudou muito nos últimos anos?", video: "fGtQ1DuFDaI", pergunta: [154, 92, 199]},
  {name: "Por que as religiões afro são mal vistas em São Caetano?", video: "JLlSXMeOMrM", pergunta: [161, 163, 224]},
  {name: "Como o preconceito se reflete na religião?", video: "KItvuIkosog", pergunta: [163, 222, 262]},
  {name: "Como se sutenta o trabalho social do terreiro?", video: "ozGOVw2-ssc", pergunta: [157, 165, 222]},
  {name: "Tem outros terreiros que resistem em São Caetano?", video: "6o72zYEPsWA", pergunta: [156, 162, 225]},
  {name: "Religiões de matriz africana sofrem apropriação cultura?", video: "zaVQFx_Gkng", pergunta: [165, 107, 228]},
  {name: "É possível enfrenter o preconceito contra as religiões de matriz africana?", video: "YkuUOiUy5CE", pergunta: [155, 168, 164]},
  {name: "Religião de matriz africana cultua as imagens de santos?", video: "YbNqFb_CrR4", pergunta: [161, 151, 224]},
  {name: "Religião de matriz africana cultua demônios?", video: "SDs47xAn0Fw", pergunta: [164, 160, 168]},
  {name: "Qual a melhor Religião matriz africana?", video: "gbMYlXjtyLo", pergunta: [163, 158, 216]},
  {name: "Toda religião de matriz africana é igualmente discriminada?", video: "udDazs1CtmQ", pergunta: [164, 168, 226]},
  {name: "O que é o Exu?", video: "v3sdBUfE0Tg", pergunta: [224, 159, 155]},
  {name: "Brancos podem cultuar religiões de matriz africana?", video: "xvZs3UhR89o", pergunta: [166, 152, 249]},
  {name: "Quem cultua religião de matriz africana também sofre racismo?", video: "ourWLu2unFs", pergunta: [165, 223, 221]},
  {name: "O que foi o projeto João de Barro?", video: "pMrITlHpCo4", pergunta: [279, 92, 153]},
  {name: "Quem cultua Religião de matriz africana é espírita?", video: "tLLaafVqJ0Q", pergunta: [160, 158, 224]},
  {name: "Indígenas podem viver na cidade?", video: "iSeMd8kgUjU", pergunta: [170, 8, 148]},
  {name: "Por que o indígena veio pra cidade?", video: "cu6V6Z1pUQ8", pergunta: [171, 179, 148]},
  {name: "Como é a vida de um indígena urbano?", video: "BHFYQ4prc4I", pergunta: [183, 179, 205]},
  {name: "Por onde passava o caminho da terra sem males?", video: "G4MKRlHmWus", pergunta: [173, 177, 140]},
  {name: "São Caetano era um território indígena?", video: "PswpiKFHJ4s", pergunta: [177, 182, 138]},
  {name: "Por que os italianos vieram pra ca?", video: "1qC7VFSUIJ0", pergunta: [70, 175, 103]},
  {name: "Já tinha gente em São Caetano antes da fazenda benditina?", video: "hlwZK8Ulf3M", pergunta: [84, 80, 173]},
  {name: "Os indígenas resistiram à colonização?", video: "OQNg2XXVEMs", pergunta: [181, 182, 11]},
  {name: "Quais povos indígenas habitavam essa região?", video: "X9-8UsEt2Iw", pergunta: [172, 180, 145]},
  {name: "Os noderstinos chegam em São Caetano com a insudtrialização?", video: "hziw3iu58tw", pergunta: [53, 59, 86]},
  {name: "Por que é raro conhecermos indígenas na cidade?", video: "dG8RxgBtUiE", pergunta: [171, 206, 184]},
  {name: "Quais povos indígenas vivem hoje em São Caetano?", video: "i7CUpjrVd7w", pergunta: [186, 134, 181]},
  {name: "Os indígenas são muito invisibilzados na história do Brasil?", video: "DLOLGMhIzt8", pergunta: [182, 51, 140]},
  {name: "Para que conhecer a história indígena?", video: "2bXwWMVh_7A", pergunta: [144, 3, 185]},
  {name: "Quais povos indígenas vivem hoje na região do ABC?", video: "01Vsza7MqoE", pergunta: [139, 150, 186]},
  {name: "A mulher indígena sofre muito preconceito?", video: "6M731B42le4", pergunta: [179, 145, 206]},
  {name: "Todo ritual indigena é xamanista?", video: "6mk4NNJmGzM", pergunta: [136, 102, 155]},
  {name: "É importante realizar o auto-reconhecimento?", video: "x7shEiPZB-M", pergunta: [271, 205, 181]},
  {name: "Tem emprego em São Caetano?", video: "hkApGgxoR5E", pergunta: [200, 231, 209]},
  {name: "Tem preconceito de bairro em São Caetano?", video: "7rBLqCs6Qwg", pergunta: [13, 241, 207]},
  {name: "Hoje tem acolhimento para os nordestinos?", video: "CuNh-B0YFc8", pergunta: [190, 46, 231]},
  {name: "Ainda vem muitos nordestinos para São Caetano?", video: "lPDkrQ1Baac", pergunta: [189, 187, 194]},
  {name: "São Caetano é uma cidade cara?", video: "-dJRNgO0Dnc", pergunta: [89, 94, 192]},
  {name: "A construção do shopping melhorou o bairro cerâmica?", video: "FgXH0WVf9ds", pergunta: [75, 77, 191]},
  {name: "Tinha cultura popular antigamente em São Caetano?", video: "QCmpEorL2ys", pergunta: [98, 244, 261]},
  {name: "Como é a festa nordestina?", video: "YVzwdC_gHhY", pergunta: [15, 18, 19]},
  {name: "Todo nordestino gosta de comida nordestina?", video: "DAMTTR1C8G0", pergunta: [45, 6, 234]},
  {name: "Como era a infância antigamente em São Caetano?", video: "V-7GsMXl1D0", pergunta: [3, 198, 199]},
  {name: "Como era o buracão da cerâmica?", video: "ln_afTTXubM", pergunta: [196, 75, 201]},
  {name: "Mudou muita coisa na cidade nos últimos anos?", video: "WO0CS7Cx8EY", pergunta: [199, 212, 201]},
  {name: "Por quê São Caetano mudou tanto?", video: "77BbIU6M-B8", pergunta: [200, 211, 193]},
  {name: "Antigamente tinha mais empregos?", video: "we84LX5HUd4", pergunta: [201, 231, 209]},
  {name: "Muitas fábricas fecharam em São Caetano?", video: "qrIe6ttUmmw", pergunta: [200, 232, 210]},
  {name: "O cenário urbano mudou muito hoje em dia?", video: "kT_LIkP56H4", pergunta: [211, 203, 204]},
  {name: "A convicência com os vizinhos era diferente antigamente?", video: "u1LrjwM-vVI", pergunta: [153, 235, 92]},
  {name: "No passado tinha muita cultura negra na cidade?", video: "uaglPKJk3lg", pergunta: [268, 109, 235]},
  {name: "É fácil se autoidentificar indígena?", video: "0uV0QkuITrs", pergunta: [206, 184, 271]},
  {name: "O que você sabe da sua ascendência indígena?", video: "Bm86d1b3hcc", pergunta: [205, 275, 8]},
  {name: "Tem preconceito de gênero em São Caetano?", video: "8SVv4ldnERI", pergunta: [10, 154, 208]},
  {name: "Como o preconceito se manifesta em São Caetano?", video: "MKfZBejpkX4", pergunta: [207, 188, 93]},
  {name: "Como eram as condições de trabalho nas fábricas de São Caetano?", video: "H3EpYVovrL8", pergunta: [232, 187, 210]},
  {name: "Por que a antiga fábrica da Matarazzo tem o solo contaminado?", video: "N7k3i9PGJF4", pergunta: [280, 212, 232]},
  {name: "Antigamente tinha muitos rios em São Cartano?", video: "Bs0cft-suJA", pergunta: [212, 173, 202]},
  {name: "O progresso da cidade alterou muito o cenário urbano?", video: "z4ffx1ZThjs", pergunta: [213, 211, 196]},
  {name: "Antigamente tinha muitos cortiços em São Caetano?", video: "SgmeHlKV_Vw", pergunta: [214, 60, 279]},
  {name: "Os antigos moradores de cortiço foram expulsos de São Caetano?", video: "PCnY4rxKHBw", pergunta: [78, 213, 281]},
  {name: "Qual a origem dos negros de São Caetano?", video: "6uslVgKnXG0", pergunta: [217, 242, 152]},
  {name: "Como é a cultura afro-brasielira?", video: "xIEtL1PNa1c", pergunta: [218, 12, 219]},
  {name: "Por que os negros foram escravizados?", video: "yMElBq4T86w", pergunta: [218, 109, 258]},
  {name: "Todos negros escravizados eram tratados de forma igual?", video: "zG1SIRvqTL4", pergunta: [221, 120, 233]},
  {name: "A forma de se vestir também é cultura?", video: "9OXsMek_WaE", pergunta: [225, 216, 9]},
  {name: "Por que reverenciar aos antepassados?", video: "FoXPpdkYFi8", pergunta: [222, 118, 226]},
  {name: "Por que os negros recebem tantos rótulos negativos?", video: "bnIetvFLkU0", pergunta: [105, 273, 103]},
  {name: "Por que ter o Candomblé como referência?", video: "yTtTy3AxLps", pergunta: [220, 226, 9]},
  {name: "Os negros também podem ser racistas?", video: "6WYvSthDJfs", pergunta: [249, 228, 227]},
  {name: "Religiões Afro cultuam os elementos da natureza?", video: "LpW9kauaOF0", pergunta: [164, 168, 226]},
  {name: "O que simbolizam as roupas do candomblé?", video: "_t_xiWDTLbQ", pergunta: [219, 158, 155]},
  {name: "O que simbolizam os paramentos do candomblé?", video: "OsPS4h2jbtQ", pergunta: [222, 161, 263]},
  {name: "A cultura negra é aceita em São Caetano?", video: "cBYfDM-Fr6o", pergunta: [237, 188, 276]},
  {name: "Qualquer pessoa pode falar sobre raça?", video: "aMt4qFXn91w", pergunta: [10, 249, 165]},
  {name: "Por que a educação é importante?", video: "rvtymaHBElA", pergunta: [219, 184, 259]},
  {name: "Como era a vinda de um nordestino?", video: "I-mqS_foKrc", pergunta: [53, 83, 231]},
  {name: "Como era pra procurar emprego antigamente?", video: "BUEaCweMVXE", pergunta: [200, 232, 209]},
  {name: "Antigamente tinham outros trabalhos que não nas fábricas?", video: "uUOqO4PCETs", pergunta: [200, 235, 121]},
  {name: "Como conviver com o racismo?", video: "uBMKoz0UO9Q", pergunta: [272, 1, 48]},
  {name: "Os nordestinos faziam muitas festas?", video: "JPoqX2fvRBA", pergunta: [235, 213, 57]},
  {name: "Antigamente tinha solidariedade entre os negros em São Caetano?", video: "V-bxD1h8_tY", pergunta: [231, 46, 120]},
  {name: "Mudou muita coisa na cidade?", video: "w1kyJ1dPbys", pergunta: [73, 199, 4]},
  {name: "Por que fazer samba?", video: "IwddXb4ZZF8", pergunta: [259, 239, 238]},
  {name: "Como se faz uma festa na rua?", video: "26vXI8RY-ek", pergunta: [237, 253, 71]},
  {name: "Como se organiza uma festa autônoma?", video: "Kv1u7-IQuog", pergunta: [241, 18, 235]},
  {name: "Os sambistas sofrem discriminação?", video: "rP0kBsFqr04", pergunta: [1, 20, 241]},
  {name: "As pessoas discriminam as comunidades?", video: "AymBIjGNWsU", pergunta: [242, 188, 60]},
  {name: "Quais os bairros com mais negros em São Caetano?", video: "FraVw_MnNWc", pergunta: [215, 72, 12]},
  {name: "Como mora a população pobre se São Caetano?", video: "DTVtR4eRyn0", pergunta: [167, 279, 60]},
  {name: "Cultura popular tem valor?", video: "Cf7LEEFfI2c", pergunta: [5, 165, 252]},
  {name: "O que é a capoeira?", video: "EHy5yaqLfkE", pergunta: [246, 124, 27]},
  {name: "A capoeira é um jogo perigoso?", video: "C4XlA49jth8", pergunta: [36, 267, 44]},
  {name: "O que é mandinga?", video: "c-2J7GVf9M8", pergunta: [131, 263, 43]},
  {name: "Como combater o preconceito cotra a capoeira?", video: "DZyxTO-Pp24", pergunta: [254, 100, 101]},
  {name: "Qual a diferença entre racismo e preconceito?", video: "jNK_uvawu24", pergunta: [223, 272, 228]},
  {name: "São Caetano valoriza a cultura popular?", video: "zUfWGv9hpl4", pergunta: [253, 98, 252]},
  {name: "Capoeira é religião?", video: "2kylj4n6kDQ", pergunta: [131, 34, 155]},
  {name: "O que é o Conselho Municipal de Cultura?", video: "97qLiI-m5po", pergunta: [253, 274, 30]},
  {name: "Por que a prefeitura não incentiva mais a cultura popular?", video: "rX3La6UtENg", pergunta: [256, 257, 5]},
  {name: "O que a capoeira pode mudar na vida de uma pessoa?", video: "m-dO98Kge-0", pergunta: [41, 245, 106]},
  {name: "Quais manifestações culturais se relacionam com a capoeira?", video: "Ghj5kuIHlZs", pergunta: [40, 111, 112]},
  {name: "Tem maracatu em São Caetano?", video: "QOwSAIC_R-c", pergunta: [114, 112, 227]},
  {name: "Como combater o preconceito contra a cultura popular?", video: "sjWt0Jsql8w", pergunta: [244, 240, 269]},
  {name: "Ainda existe racismo no Brasil?", video: "kAuCifWo7sA", pergunta: [223, 273, 94]},
  {name: "Pra que serve a educação?", video: "w1rXP1IKt-k", pergunta: [258, 229, 117]},
  {name: "A raíz cultural de São Caetano não é européia?", video: "APj4PeE4-0s", pergunta: [116, 102, 276]},
  {name: "Como a cultura popular sobrevive?", video: "31kf8xCQAlk", pergunta: [266, 250, 11]},
  {name: "Por que a religião afro é tão discriminada?", video: "sQi-ikHwv2U", pergunta: [163, 251, 247]},
  {name: "Religião de matriz africana é macumba?", video: "t97fHbvGd0U", pergunta: [131, 262, 185]},
  {name: "Por que a cultura popular tem relação com a cultura africana?", video: "ExHaMVKUk8w", pergunta: [265, 146, 268]},
  {name: "A capoeira é africana?", video: "iOu13WZhVlA", pergunta: [23, 127, 104]},
  {name: "Como alguém se torna um mestre na cultura popular?", video: "8dq1qjoAEpA", pergunta: [106, 28, 19]},
  {name: "Por que a capoeira era proibida?", video: "rx6tqCvyY4I", pergunta: [99, 36, 79]},
  {name: "Qual a relação entre grafitti e cultura negra?", video: "FdTaBwCZWc0", pergunta: [269, 270, 244]},
  {name: "Qual a diferença entre grafitti e pixação?", video: "zK9xhy6vHzM", pergunta: [268, 101, 270]},
  {name: "Por que fazer grafitti?", video: "qGBCvMEpxGg", pergunta: [269, 268, 239]},
  {name: "É importante realizar o auto-reconhecimento?", video: "9qXEeREQd_8", pergunta: [186, 205, 275]},
  {name: "É possível enfrentar o racismo?", video: "eWxBB6sPRSQ", pergunta: [123, 233, 258]},
  {name: "Por que o povo negro é mais pobre?", video: "r5yKDMAJRO0", pergunta: [217, 218, 69]},
  {name: "Pra que servem os movimentos sociais?", video: "dq6JPd5Swxo", pergunta: [79, 11, 95]},
  {name: "Como realizar o auto-reconhecimento?", video: "x03apDoPDFs", pergunta: [271, 205, 63]},
  {name: "Onde está a cultura negra?", video: "evPKLZYlEMs", pergunta: [204, 216, 107]},
  {name: "Qual foi o primeiro terreiro de matriz africana em São Caetano?", video: "w2-PchRYHrs", pergunta: [159, 9, 222]},
  {name: "O que foi o clube Luiz Gama?", video: "fYCqLRDD_8I", pergunta: [71, 123, 235]},
  {name: "Tem moradia popular em São Caetano?", video: "IoZ50Dt_xeM", pergunta: [243, 264, 213]},
  {name: "O terreno da antiga fábrica da Matarazzo está condenado?", video: "wGSq_fa9MZQ", pergunta: [210, 4, 201]},
  {name: "É possível mudar a cidade sem expulsar a população local?", video: "B6yLoCfSHVM", pergunta: [167, 85, 274]}
];
